//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod app;
pub mod bit;
pub mod comment;
pub mod course;
pub mod course_connection;
pub mod dependency;
pub mod feedback;
pub mod file;
pub mod invitations;
pub mod invite_link;
pub mod join_queue;
pub mod landing_page;
pub mod membership;
pub mod meta;
pub mod node;
pub mod pat;
pub mod profile;
pub mod provider_invocation;
pub mod provider_proxy;
pub mod publication_log;
pub mod publication_request;
pub mod role;
pub mod sea_orm_active_enums;
pub mod swimlane;
pub mod swimlane_item;
pub mod technical_user;
pub mod template;
pub mod transaction;
pub mod user;
