//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::bit::Entity as Bit;
pub use super::comment::Entity as Comment;
pub use super::course::Entity as Course;
pub use super::course_connection::Entity as CourseConnection;
pub use super::dependency::Entity as Dependency;
pub use super::feedback::Entity as Feedback;
pub use super::invitations::Entity as Invitations;
pub use super::invite_link::Entity as InviteLink;
pub use super::join_queue::Entity as JoinQueue;
pub use super::landing_page::Entity as LandingPage;
pub use super::membership::Entity as Membership;
pub use super::meta::Entity as Meta;
pub use super::node::Entity as Node;
pub use super::profile::Entity as Profile;
pub use super::project::Entity as Project;
pub use super::project_api_key::Entity as ProjectApiKey;
pub use super::provider_invocation::Entity as ProviderInvocation;
pub use super::provider_proxy::Entity as ProviderProxy;
pub use super::publication_log::Entity as PublicationLog;
pub use super::publication_request::Entity as PublicationRequest;
pub use super::role::Entity as Role;
pub use super::swimlane::Entity as Swimlane;
pub use super::swimlane_item::Entity as SwimlaneItem;
pub use super::template::Entity as Template;
pub use super::user::Entity as User;
pub use super::user_api_key::Entity as UserApiKey;
