//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::ProjectStatus;
use super::sea_orm_active_enums::ProjectVisibility;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub status: ProjectStatus,
    pub visibility: ProjectVisibility,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i32,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i32,
    pub version: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    pub price: i32,
    pub media: Option<Vec<String>>,
    #[sea_orm(column_name = "defaultRoleId", column_type = "Text", unique)]
    pub default_role_id: String,
    #[sea_orm(column_name = "ownerRoleId", column_type = "Text", unique)]
    pub owner_role_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bit::Entity")]
    Bit,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::course_connection::Entity")]
    CourseConnection,
    #[sea_orm(has_many = "super::feedback::Entity")]
    Feedback,
    #[sea_orm(has_many = "super::invitations::Entity")]
    Invitations,
    #[sea_orm(has_many = "super::invite_link::Entity")]
    InviteLink,
    #[sea_orm(has_many = "super::join_queue::Entity")]
    JoinQueue,
    #[sea_orm(has_many = "super::membership::Entity")]
    Membership,
    #[sea_orm(has_many = "super::meta::Entity")]
    Meta,
    #[sea_orm(has_many = "super::project_api_key::Entity")]
    ProjectApiKey,
    #[sea_orm(has_many = "super::publication_request::Entity")]
    PublicationRequest,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::DefaultRoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Role2,
    #[sea_orm(
        belongs_to = "super::role::Entity",
        from = "Column::OwnerRoleId",
        to = "super::role::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Role1,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::course_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseConnection.def()
    }
}

impl Related<super::feedback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feedback.def()
    }
}

impl Related<super::invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitations.def()
    }
}

impl Related<super::invite_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InviteLink.def()
    }
}

impl Related<super::join_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinQueue.def()
    }
}

impl Related<super::membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Membership.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl Related<super::project_api_key::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectApiKey.def()
    }
}

impl Related<super::publication_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicationRequest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
