//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "SwimlaneItem")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "swimlaneId", column_type = "Text")]
    pub swimlane_id: String,
    pub order: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub content: Option<Json>,
    #[sea_orm(column_name = "bitId", column_type = "Text", nullable)]
    pub bit_id: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bit::Entity",
        from = "Column::BitId",
        to = "super::bit::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Bit,
    #[sea_orm(
        belongs_to = "super::swimlane::Entity",
        from = "Column::SwimlaneId",
        to = "super::swimlane::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Swimlane,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl Related<super::swimlane::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Swimlane.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
