//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Dependency")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "bitId", column_type = "Text")]
    pub bit_id: String,
    #[sea_orm(column_name = "dependencyId", column_type = "Text")]
    pub dependency_id: String,
    #[sea_orm(column_type = "Text")]
    pub hub: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bit::Entity",
        from = "Column::BitId",
        to = "super::bit::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Bit,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
