//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod bit;
pub mod comment;
pub mod course;
pub mod course_connection;
pub mod dependency;
pub mod llm_parameters;
pub mod membership;
pub mod meta;
pub mod node;
pub mod profile;
pub mod project;
pub mod provider_proxy;
pub mod role;
pub mod sea_orm_active_enums;
pub mod template;
pub mod user;
