//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::bit::Entity as Bit;
pub use super::comment::Entity as Comment;
pub use super::course::Entity as Course;
pub use super::course_connection::Entity as CourseConnection;
pub use super::dependency::Entity as Dependency;
pub use super::llm_parameters::Entity as LlmParameters;
pub use super::membership::Entity as Membership;
pub use super::meta::Entity as Meta;
pub use super::node::Entity as Node;
pub use super::profile::Entity as Profile;
pub use super::project::Entity as Project;
pub use super::provider_proxy::Entity as ProviderProxy;
pub use super::role::Entity as Role;
pub use super::template::Entity as Template;
pub use super::user::Entity as User;
