//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use super::sea_orm_active_enums::ProjectStatus;
use super::sea_orm_active_enums::ProjectVisibility;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub status: ProjectStatus,
    pub visibility: ProjectVisibility,
    #[sea_orm(column_type = "Text", nullable)]
    pub changelog: Option<String>,
    pub attributes: Option<Vec<String>>,
    pub permissions: i64,
    #[sea_orm(column_name = "ratingSum")]
    pub rating_sum: i32,
    #[sea_orm(column_name = "ratingCount")]
    pub rating_count: i32,
    pub version: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bit::Entity")]
    Bit,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::course_connection::Entity")]
    CourseConnection,
    #[sea_orm(has_many = "super::membership::Entity")]
    Membership,
    #[sea_orm(has_many = "super::meta::Entity")]
    Meta,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::course_connection::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CourseConnection.def()
    }
}

impl Related<super::membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Membership.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
