//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::BitType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Bit")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    pub r#type: BitType,
    #[sea_orm(column_type = "Text", nullable)]
    pub repository: Option<String>,
    #[sea_orm(column_name = "downloadLink", column_type = "Text", nullable)]
    pub download_link: Option<String>,
    #[sea_orm(column_name = "fileName", column_type = "Text", nullable)]
    pub file_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub hash: String,
    pub size: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub hub: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub version: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    #[sea_orm(column_name = "dependencyTreeHash", column_type = "Text", unique)]
    pub dependency_tree_hash: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    pub dependencies: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub parameters: Option<Json>,
    pub authors: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bit_cache::Entity")]
    BitCache,
    #[sea_orm(has_one = "super::bit_tree_cache::Entity")]
    BitTreeCache,
    #[sea_orm(has_many = "super::meta::Entity")]
    Meta,
    #[sea_orm(has_one = "super::provider_proxy::Entity")]
    ProviderProxy,
    #[sea_orm(has_many = "super::swimlane_item::Entity")]
    SwimlaneItem,
}

impl Related<super::bit_cache::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BitCache.def()
    }
}

impl Related<super::bit_tree_cache::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BitTreeCache.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl Related<super::provider_proxy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProviderProxy.def()
    }
}

impl Related<super::swimlane_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SwimlaneItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
