//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "BitCache")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "bitId", column_type = "Text", nullable)]
    pub bit_id: Option<String>,
    #[sea_orm(column_name = "externalBit", column_type = "JsonBinary", nullable)]
    pub external_bit: Option<Json>,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "dependencyTreeHash", column_type = "Text")]
    pub dependency_tree_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bit::Entity",
        from = "Column::BitId",
        to = "super::bit::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Bit,
    #[sea_orm(
        belongs_to = "super::bit_tree_cache::Entity",
        from = "Column::DependencyTreeHash",
        to = "super::bit_tree_cache::Column::DependencyTreeHash",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BitTreeCache,
}

impl Related<super::bit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bit.def()
    }
}

impl Related<super::bit_tree_cache::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BitTreeCache.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
